name = "EigenvalueSolver"
uuid = "678e3805-c322-49de-aa76-96beab6c89e5"
authors = ["Matias Bender and Simon Telen"]
version = "0.1.0"

[deps]
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
GenericSVD = "01680d73-4ee2-5a08-a1aa-533608c188bb"
GenericSchur = "c145ed77-6b09-5dd9-b285-bf645a82121e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polymake = "d720cf60-89b5-51f5-aff5-213f193123e7"
SmithNormalForm = "ba71f38f-f508-439b-ac77-437f86a20aa1"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TaylorSeries = "6aa5eb33-94cf-58f4-a9d0-e4b2c4fc25ea"
